//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dicta
    {
        public int iddicta { get; set; }
        public Nullable<int> idcurso { get; set; }
        public Nullable<int> idprofesor { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
