//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class colegioEntities1 : DbContext
    {
        public colegioEntities1()
            : base("name=colegioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<dicta> dicta { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
        public virtual DbSet<matricula> matricula { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
